#pragma once
#include "ecs/system.h"

DEFINE_COMPONENT_ID(Bow, 25)
DEFINE_COMPONENT_ID(Arrow, 26)
DEFINE_COMPONENT_ID(FPSController, 27)
DEFINE_COMPONENT_ID(Player, 28)
DEFINE_COMPONENT_ID(PlayerInput, 29)
