#pragma once
#include "ecs/system.h"

DEFINE_COMPONENT_ID(Bow, 30)
DEFINE_COMPONENT_ID(Arrow, 31)
DEFINE_COMPONENT_ID(FPSController, 32)
DEFINE_COMPONENT_ID(Player, 33)
DEFINE_COMPONENT_ID(PlayerInput, 34)
